### ISSUE TITLE
Remove icons in menu links under main banner images

### ISSUE THREAD

**Issue by tweettypography** [tweettypography/oktoberfesthmpf#14]
These were intended to be image thumbnails. Text will work for now.

**Comment by matadur** [comment]
Are you talking about these?
![beer_icon](https://f.cloud.github.com/assets/2113643/921575/c77c7596-fefe-11e2-86f8-759cf941bdf5.jpg)

**Comment by tweettypography** [comment]
Yes

**Comment by matadur** [comment]
I've done this, but not sure if I get the concept.

**Comment by thepkpnthr** [comment]
My 2 cents here.... we'd intended that these be images, but as Mayowa & I
spoke at Thirsty Scholar, we looked at what the images (if we used the
pictures we had & shrunk them) would look like when we shrunk them small
enough to be buttons.  We found they were illegible.  Mayowa suggeted
overlaying them with white text stating the name of the section.  When I
did that, then you REALLY couldn't see the picture, so I figured, why have
it at all?  I changed the background to a solid color that matched the
color filter I used on the pictures.

If you still want pictures instead of text icons, I recommend that we don't
use the pictures we've currently got in DropBox.  We'll need very simple
single-subject pictures or icons to make it clear what the viewer is
looking at.  An example would be just a glass of beer for the "BEER"
section or a guitar for the "MUSIC" section.

If you want to develop this idea further, let me know.  Otherwise, the call
was to go with the text & solid background icons.
~Ryan

**Comment by tweettypography** [comment]
Actually, the single-subjuct picture is exactly what I was picturing. But I've since decided that second menu is redundant in the first place. Going to focus the links in the header instead and use that cutout section for a headline. We can discuss at the meeting tonight.

**Comment by thepkpnthr** [comment]
I think that's a good call to delete the header links... They do seem
redundant.

Shoot!  I thought the meeting was next week!  I've got a business meeting
tonight so I'm not going to be able to make it.  Can you let me know what
comes out of it?  Or anything else you need from me on GitHub.  Otherwise
I'll check online to see the website!

Ryan
