### ISSUE TITLE
Each section needs its own background

### ISSUE THREAD

**Issue by tweettypography** [tweettypography/oktoberfesthmpf#21]
Each sections should have a full-width background image that extends the height of the section. When the background image reaches the top it should stop scrolling and the content should scroll over it (just like the header images does now). The next background image in line should _also_ scroll over it, so it gets slowly covered up. Alternately, we could make the background image fill the entire screen and then have it it cross fade when a new section gains focus. Which do you think would be best?

**Comment by tweettypography** [comment]
The more I think about it, the more I like the second concept better. Basic concept: There's a full-width, full-height background image for every section. Rolling over the links in the header will fade the corresponding image in. Clicking the link will keep the corresponding image in place while scrolling to that section. Scrolling to the section manually will fade between the backgrounds of whichever section gets within 20% of the top of the screen. The center content area will remain white or will be somewhat translucent (may need to do some testing - maybe the sections which are not the current active one should be translucent and the active one should be solid?)

**Comment by matadur** [comment]
I like both concepts.

**Comment by thepkpnthr** [comment]
Further feedback:

When we first wireframed, we said we wanted 2 images... one of the left &
one on the right, each wide enough to act as a border (these are all the
filtered images I developed), but that in the center column where the text
& content would go, we were going to leave it white or potentially the
color of the filter.

Are you suggesting that we have just 1 full-width image that the text &
content sits on top of?  If this is the case, can there be a translucent
center column so that the text is legible on top of the image?

I like both of your transition concepts, but think I prefer the 2nd one.
~Ryan

**Comment by tweettypography** [comment]
Yes, you're picturing it correctly. The center column will either be solid white or just slightly transparent - don't want to make it difficult to see the content. I modified a few of your images to make them work in this way - can demo for you.

**Comment by thepkpnthr** [comment]
Sounds good!

**Comment by matadur** [comment]
closing
